FROM node
WORKDIR /code

COPY . .
#COPY package.json .

RUN npm install --silent

ENV NODE_PATH=.
EXPOSE 3000

CMD ["node","run.js"]

#Bæta við export path
#keyra vantar runþjs file inn
#export PATH=~/opt/bin:$PATH
# RUN export PATH=$PATH:~/opt/bin:~/opt/node/bin
