version: '2'
services:
  server:
    environment:
      - 'PGPOST=NODE_ENV'                       #Production
      - 'POSTGRES_PORT=5432'                    #Postgres port is 5432
      - 'PORT=80'                               #Port for AWS
    image: 'sandras15/tictactoe:${GIT_COMMIT}'  #The Docker image with git commit tag
    depends_on:
      - postgres                                #Connects server and postgres
    ports:
      - "80:80"                                 #AWS port
      - "8080:8080"                             #Server port
  postgres:
    image: postgres                             #Image for postgres
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'    #Password for postgres
    ports:
      - "5432:5432"                             #Postgres port
