version: '2'
services:
  server:
    environment:
      - NODE_ENV=production                       #Production
      - POSTGRES_PORT=5432                      #Postgres port is 5432
      - PORT=80                                 #Port for AWS
    image: 'sandras15/tictactoe:${GIT_COMMIT}'  #The Docker image with git commit tag
    depends_on:
      - postgres                                #Connects server and postgres
    ports:
      - "80:80"                                 #AWS port
      - "8080:8080"                             #Server port
  postgres:
    image: postgres                             #Image for postgres
    environment:
      - POSTGRES_USER=postgres                  #User for postgres
      - POSTGRES_PASSWORD=mysecretpassword      #Password for postgres
    ports:
      - "5432:5432"                             #Postgres port